### ISSUE TITLE
ConcurrentModificationException with Quarkus applications

### ISSUE THREAD

**Issue by mweber03** [CycloneDX/cyclonedx-gradle-plugin#106]
With [Quarkus](https://github.com/quarkusio/quarkus) applications (specifically using Quarkus 2.3+), a `ConcurrentModificationException` occurs when trying to run the Cyclonedx plugin.

Stacktrace:
```
Caused by: java.util.ConcurrentModificationException
        at org.gradle.api.internal.DefaultDomainObjectCollection$IteratorImpl.next(DefaultDomainObjectCollection.java:475)
        at org.cyclonedx.gradle.CycloneDxTask.createBom(CycloneDxTask.java:174)
```

Reproduce
1. Clone https://github.com/mweber03/quarkus-test
2. Run `./gradlew service1:cyclonedxBom`

**Comment by mweber03** [comment]
@stevespringett Any ideas?

**Comment by kmoens** [comment]
I suffer the same problem. It was solved with me (not perfect sadly) by adding a dependency towards the build task as follows:

```
target.tasks.named('cyclonedxBom').configure {
    dependsOn target.tasks.named('build')
}
```

This is not perfect however, but I suspect that this happens because some of my own plugins modify / create configurations during runtime and that this somehow triggers the `ConcurrentModificationException`
