### ISSUE TITLE
metadata does not get templated

### ISSUE THREAD

**Issue by ChristianCiach** [CycloneDX/cyclonedx-gradle-plugin#119]
Using version 1.5.0 of this plugin, the `metadata` element of the generated sbom file always looks like this:

```
  "metadata" : {
    "timestamp" : "2022-03-28T18:16:01Z",
    "tools" : [
      {
        "vendor" : "${project.organization.name}",
        "name" : "${project.name}",
        "version" : "${project.version}"
      }
    ],

```

According to the source code, these attributes should be read from https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/master/src/main/resources/plugin.properties, but this template file doesn't seem to be rendered correctly.

**Comment by ThomGeG** [comment]
I've had a look and it's because the substitutions were being done as a part of the Maven builds and defined in the POM, which has since been removed:
https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/444683b2e5485af47d951d566eea9f305cd55264/pom.xml#L228-L240

The code to actually set the tooling meta-data is here: https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/c70e70c9bffcfb4f267e356f226b451900c7149c/src/main/java/org/cyclonedx/gradle/CycloneDxTask.java#L263-L265

In theory it should be a case of just migrating the configuration into the `build.gradle` so they're made again via some task/plugin.
