### ISSUE TITLE
Plugin version 1.8.0 referencing version 1.7.4 in output

### ISSUE THREAD

**Issue by 0BuRner** [CycloneDX/cyclonedx-gradle-plugin#360]
Seems you forgot to update the https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/master/src/main/resources/plugin.properties when releasing 1.8.0 with the corresponding version.

**Comment by ThomasVitale** [comment]
I can see that when moving from Groovy to Kotlin for the Gradle configuration, the code updating the `plugin.properties` file automatically has been removed: https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/305/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7L38

It would be nice to have it automatically updated. An option is to add the task back using the Kotlin syntax and make it part of the compilation step, but it would cause continuous changes to the properties file even if nothing changed (due to the autogenerated timestamp) resulting in a poor development experience. I have drafted an alternative solution to change the file only if there was any actual change: https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/363. Any thoughts on the solution?
