### ISSUE TITLE
Gradle can't still resolve the 1.1.4 Version

### ISSUE THREAD

**Issue by CleanHit** [CycloneDX/cyclonedx-gradle-plugin#57]
I can see [here](https://plugins.gradle.org/plugin/org.cyclonedx.bom) that the **1.1.4** version was published but I'm still getting the same error as described here #56. I followed the provided usage instructions from the file `README.md` that work with the **1.1.3** version and differ from the instructions provided [here](https://plugins.gradle.org/plugin/org.cyclonedx.bom). Nevertheless, I would like to make it work with instructions from the `README.md` file.

**Comment by zoubelu** [comment]
Hello, I'd like to join this issue, too. README.md references version **1.1.4** but it seems it hasn't been released yet. That last release here https://github.com/CycloneDX/cyclonedx-gradle-plugin/releases is **1.1.3**

**Comment by stevespringett** [comment]
Version 1.1.4 is available in the Gradle plugin repo. https://plugins.gradle.org/plugin/org.cyclonedx.bom

Maven Central was having issues at the time 1.1.4 was published and is not available in Central. Not sure why it's not showing up in GitHub releases - perhaps due to the build not completing due to issues with Central.
